openapi: 3.0.0
info:
  title: Interface Service APIs
  version: 1.0.0
servers:
  - url: https://localhost:3567
tags:
  - name: Orchestration
    description: Orchestration APIs of Interface Service
paths:
  /interface/v1/account/create:
    post:
      summary: Create User Account
      tags:
        - Orchestration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'user'
                email:
                  type: string
                  format: email
                  example: 'user@shikshalokam.org'
                password:
                  type: string
                  example: 'passwordofuser'
                otp:
                  type: string
                  example: '672854'
                has_accepted_terms_and_conditions:
                  type: boolean
                  example: true
              required:
                - name
                - email
                - password
                - otp
                - has_accepted_terms_and_conditions
      responses:
        '200':
          description: User Account Created Successfully
          content:
            application/json:
              example:
                access_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
                refresh_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
                user:
                  id: 8
                  email: user@shikshalokam.org
                  email_verified: 'false'
                  name: user
                  status: ACTIVE
                  has_accepted_terms_and_conditions: true
                  preferred_language:
                    value: english
                    label: English
                  organization_id: 1
                  roles:
                    - 2
                  user_created_at: '2023-09-20T11:59:37.871Z'
                  user_updated_at: '2023-09-20T11:59:37.871Z'
                  user_roles:
                    - id: 2
                      title: mentor
                      user_type: 0
                      status: ACTIVE
                  profile_updated_at: '2023-09-20T12:00:46.533Z'
                  profile_created_at: '2023-09-20T12:00:46.533Z'
  /interface/v1/account/update:
    post:
      summary: Update User Profile
      tags:
        - Orchestration
      parameters:
        - name: X-auth-token
          in: header
          description: Bearer JWT token for authentication
          required: true
          schema:
            type: string
            format: JWT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'ShikshaLokam User'
                location:
                  type: array
                  items:
                    type: string
                  example:
                    - 'AP'
                    - 'KL'
                about:
                  type: string
                  example: 'This is test about of mentee'
                gender:
                  type: string
                  example: 'male'
                image:
                  type: string
                  example: 'https://cloudstorage.com/container/abc.png'
                languages:
                  type: array
                  items:
                    type: string
                  example:
                    - 'english'
                    - 'hindi'
                designation:
                  type: string
                  example: 'Lead Mentor'
                area_of_expertise:
                  type: array
                  items:
                    type: string
                  example:
                    - 'technology'
                    - 'leadership'
                education_qualification:
                  type: array
                  items:
                    type: string
                  example:
                    - 'MBA'
                    - 'B.Tech'
                age:
                  type: integer
                  example: 35
                experience:
                  type: string
                  example: '10 years'
                tags:
                  type: array
                  items:
                    type: string
                  example:
                    - 'Experienced'
                    - 'Technical'
                configs:
                  type: object
                  properties:
                    notification:
                      type: boolean
                      example: true
                    visibility:
                      type: string
                      enum:
                        - public
                        - private
                      example: 'public'
              required:
                - name
      responses:
        '200':
          description: User Profile Updated Successfully
          content:
            application/json:
              example:
                id: '8'
                name: ShikshaLokam User
                location:
                  - value: AP
                    label: Andhra Pradesh
                  - value: KL
                    label: Kerala
                about: This is test about of mentee
                has_accepted_terms_and_conditions: true
                gender:
                  value: male
                  label: Male
                image: 'https://cloudstorage.com/container/abc.png'
                languages:
                  - value: english
                    label: English
                user_created_at: '2023-09-20T11:59:37.871Z'
                user_updated_at: '2023-09-20T11:59:37.871Z'
                designation: Lead Mentor
                area_of_expertise:
                  - value: technology
                    label: Technology
                  - value: leadership
                    label: Leadership
                education_qualification:
                  - value: mba
                    label: MBA
                  - value: btech
                    label: B.Tech
                rating:
                  average: 5
                  count: 20
                age: 35
                experience: 10 years
                stats:
                  sessions_attended: 50
                  students_mentored: 30
                tags:
                  - experienced
                  - technical
                configs:
                  notification: true
                  visibility: public
                visibility: visible
                organisation_ids:
                  - 1
                  - 2
                external_session_visibility: limited
                external_mentor_visibility: hidden
                profile_created_at: '2023-09-20T12:00:46.533Z'
                profile_updated_at: '2023-09-20T12:17:12.316Z'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
